spring:
  application:
    name: mytest    # 应用名称
  mandatory-file-encoding: UTF-8    # 强制所有文件UTF-8编码，gradle bootRun启动时可能会报错"The Java Virtual Machine has not been configured to use the desired default character encoding (UTF-8)"，需要加参数'-Dfile.encoding=UTF-8'，gradle bootRun -Dfile.encoding=UTF-8
  http:
    encoding:
      enabled: true
      charset: UTF-8

server:
  port: 9090

# 自定义配置
myConfig:
  myObject:
    myName: zhangsan
    myAge: 25
